apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfe-app
spec:
  selector:
    matchLabels:
      app: pfe-app
  replicas: 1
  template:
    metadata:
      labels:
        app: pfe-app
    spec:
      containers:
        - name: pfe-app
          image: "hasnaoui68/node-app-2.0"
          env:
            - name: MONGO_URL
              value: "mongodb://192.168.1.23:30000/users"
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: pfe-app-service
spec:
  selector:
    app: pfe-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 31000
